"""Remove clicks column from shortened_urls

Revision ID: 3bbb10439b94
Revises: 10391ce1bd5d
Create Date: 2025-04-18 19:40:45.009107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbb10439b94'
down_revision: Union[str, None] = '10391ce1bd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortened_urls', 'clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
