apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
data:
  KAFKA_URL: "host.docker.internal:9092"
  KAFKA_TOPIC_URL_VALIDATION: "url_validation_requests"
  KAFKA_GROUP_ID: "url_validator_group"
  KAFKA_TOPIC_VALIDATION_RESULT: "url_validation_result"
  MONGO_DB_NAME: "url_validator"
  MONGO_COLLECTION_NAME: "validation_data"

