# project name
name: url-shortener

services:
  mongo:
    image: mongo:6.0
    container_name: url_shortener_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: