# project name
name: url-shortener

services:
  postgres:
    image: postgres:16
    container_name: url_shortener_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
