# project name
name: url-shortener

services:
  redis:
    image: redis:latest
    container_name: url_shortener_redis-cache
    restart: always
    ports:
      - "6379:6379"
    # save if was a change in 20s
    command:
      - redis-server
      - --save
      - "20"
      - "1"
      - --loglevel
      - warning
      - --maxmemory
      - 100mb
      - --maxmemory-policy
      - allkeys-lru
      - --appendfsync
      - everysec
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - url-shortener_url_shortener_network

networks:
  url-shortener_url_shortener_network:
    external: true
